# Generated by Django 5.2 on 2025-04-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField(unique=True)),
                ("abbreviation", models.CharField(max_length=3)),
                ("city", models.CharField(max_length=50)),
                ("conference", models.CharField(max_length=10)),
                ("division", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("position", models.CharField(blank=True, max_length=10, null=True)),
                ("height_feet", models.IntegerField(blank=True, null=True)),
                ("height_inches", models.IntegerField(blank=True, null=True)),
                ("height_total_inches", models.IntegerField(blank=True, null=True)),
                ("weight_pounds", models.IntegerField(blank=True, null=True)),
                (
                    "jersey_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("draft_year", models.IntegerField(blank=True, null=True)),
                ("draft_round", models.IntegerField(blank=True, null=True)),
                ("draft_number", models.IntegerField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="nba_data.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField(unique=True)),
                ("date", models.DateField()),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("home_team_score", models.IntegerField()),
                ("visitor_team_score", models.IntegerField()),
                ("season", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("period", models.IntegerField(blank=True, null=True)),
                ("time", models.CharField(blank=True, max_length=10, null=True)),
                ("postseason", models.BooleanField(default=False)),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="nba_data.team",
                    ),
                ),
                (
                    "visitor_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="nba_data.team",
                    ),
                ),
            ],
        ),
    ]
